print("hola xd ")
print('Hola xd 2')
print(type(5))
print(type(5.1))
print(type(5.0))
print(type(5.))
print(type("hola"))
print(type(True))
print(type(None))
print(None)
print("##########################################################")
print("hOlA MuNdO")
print("hOlA MuNdO".upper())
print("hOlA MuNdO".lower())
print("hOlA MuNdO".title())
print("         hOlA MuNdO   ")
print("         hOlA MuNdO   ".strip())
print("         hOlA MuNdO   ".strip().title())
print("Hola Mundo".endswith("Mundo"))
print("Hola Mundo".endswith("Hola"))
print("Hola"+" Mundo")
print("Hola"*5)
print("##########################################################")
print(3+5)
print(3-5)
print(3*5)
print(6/2)
print(6//2)
print(3+5.)
print(6.//2)
print(20/6)
print(20//6)
print(10/11)
print(10//11)
print(0.1+0.2)
print(5**2)
print("##########################################################")
print("ESTO ES AND")
print(True and True)
print(True and False)
print(False and True)
print(False and False)
print("ESTO ES OR")
print(True or True)
print(True or False)
print(False or True)
print(False or False)
print("ESTO ES NOT")
print(not True)
print(not False)
print("REPRESENTACION BOOLEANA")
print(0 and True)
print(1.5 and True)
print("" and True)
print("xd" and True)
print("REPRESENTACION NOT")
print(not 5)
print(not 0)
print(not "")
print(not "xd")